baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "m10c"

[params]
  author = "x0b"
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula turpis sit amet elit pretium."
  [[params.social]]
    name = "github"
    url = "https://github.com/x0b"

# Red and black theme
  [params.style]
    darkestColor = "#d35050"
    darkColor = "#212121"
    primaryColor = "#ffffff"
    lightColor = "#a2a2a2"
    lightestColor = "#d3d3d3"
  